version: '3'

services:

  vuepress_node:
    container_name: vuepress_node
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./src:/var/www/html/src
      - ./.git:/var/www/html/.git
      - ./package.json:/var/www/html/package.json
      - ./yarn.lock:/var/www/html/yarn.lock
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: 1
      CHOKIDAR_INTERVAL: 500
      DEV: 0
